os: osx
language: generic
sudo: false
dist: trusty
osx_image:
- xcode9.4
- xcode9.3
- xcode9.2
- xcode9.1
- xcode9
env:
- SWIFT_VERSION=4.0
- SWIFT_VERSION=4.0.2
- SWIFT_VERSION=4.0.3
- SWIFT_VERSION=4.1
- SWIFT_VERSION=4.1.1
- SWIFT_VERSION=4.1.2
install:
- eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
- swift build
