os: osx
language: generic
sudo: false
dist: trusty
osx_image:
- xcode9
- xcode10
env:
- SWIFT_VERSION=4.0
- SWIFT_VERSION=4.0.2
- SWIFT_VERSION=4.0.3
- SWIFT_VERSION=4.1
- SWIFT_VERSION=4.1.1
- SWIFT_VERSION=4.1.2
- SWIFT_VERSION=4.1.3
- SWIFT_VERSION=4.2
matrix:
  exclude:
  - osx_image: xcode9
    env: SWIFT_VERSION=4.2
  allow_failures:
  - osx_image: xcode9
install:
- eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
- swift build
