os:
- osx
language: generic
sudo: false
dist: trusty
osx_image:
- xcode9.4
- xcode9.3
- xcode9.2
- xcode9.1
- xcode9
- xcode8.3
- xcode8
- xcode7.3
- xcode6.4
env:
- SWIFT_VERSION=2.2
- SWIFT_VERSION=2.2.1
- SWIFT_VERSION=3.0
- SWIFT_VERSION=3.0.1
- SWIFT_VERSION=3.0.2
- SWIFT_VERSION=3.1
- SWIFT_VERSION=3.1.1
- SWIFT_VERSION=4.0
- SWIFT_VERSION=4.0.2
- SWIFT_VERSION=4.0.3
- SWIFT_VERSION=4.1
- SWIFT_VERSION=4.1.1
- SWIFT_VERSION=4.1.2
install:
- git clone https://github.com/kylef/swiftenv.git ~/.swiftenv
- export SWIFTENV_ROOT="$HOME/.swiftenv"
- export PATH="$SWIFTENV_ROOT/bin:$PATH"
- eval "$(swiftenv init -)"
- swiftenv install "$SWIFT_VERSION" || true
- swift --version
script:
- swift build
