os: osx
language: generic
sudo: false
dist: trusty
osx_image: xcode9
env:
- SWIFT_VERSION=4.0
- SWIFT_VERSION=4.0.2
- SWIFT_VERSION=4.0.3
- SWIFT_VERSION=4.0-dev
- SWIFT_VERSION=4.1
- SWIFT_VERSION=4.1.1
- SWIFT_VERSION=4.1.2
- SWIFT_VERSION=4.1.3
- SWIFT_VERSION=4.1-dev
- SWIFT_VERSION=4.2-dev
- SWIFT_VERSION=5.0-dev
install:
- eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
- swift build
