os: osx
language: generic
sudo: false
osx_image:
- xcode9
env:
- SWIFT_VERSION=3.0
- SWIFT_VERSION=3.0.1
- SWIFT_VERSION=3.0.2
- SWIFT_VERSION=3.1
- SWIFT_VERSION=3.1.1
- SWIFT_VERSION=4.0
- SWIFT_VERSION=4.0.2
- SWIFT_VERSION=4.0.3
- SWIFT_VERSION=4.1
- SWIFT_VERSION=4.1.1
- SWIFT_VERSION=4.1.2
install:
- eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
- swift build
